### ISSUE TITLE
Include pages into the list of tagged posts

### ISSUE THREAD

**Issue by HabariImporter** [habari/habari#117]
Initially reported by: @Massimiliano as #TRAC1255 
All three bundled themes don't include pages into the list of tagged posts: if a page is tagged "foobar", the URL [site]/tag/foobar won't show the page in the list. Tags are not related to chronology, so there shouldn't be any difference between entries and pages.

**Comment by Konzertheld** [comment]
Closing because presets make it easy for everyone to determine what is displayed where and I also do not think Habari should generally output all content types.
