### ISSUE TITLE
Simple File Silo: Errors aren't submitted to message system

### ISSUE THREAD

**Issue by HabariImporter** [habari/habari#18]
Initially reported by: @Heilemann as #TRAC453 
It'd be nice if the error messages in the simple file silo were using the message system. For instance, trying to create a directory named '/' will create an error.

**Comment by Konzertheld** [comment]
I wonder if @heilemann still uses Habari and can confirm this is fixed (because it is, as I see it).

**Comment by Heilemann** [comment]
Thank you for thinking of me, but no, I'm no longer using Habari.

**Comment by Konzertheld** [comment]
Ok. As far as I can see there are no errors that get lost somewhere in the silo, also, we are going to redesign it and will run a lot of tests propably. So I close this and we can open a new one if someone comes across something.
