### ISSUE TITLE
Manage Page/Entry Search Box clearing (0.10)

### ISSUE THREAD

**Issue by HabariImporter** [habari/habari#28]
The issue below is no longer relevant, but there is a new one: When clearing the search box, you get an "Uh oh, an error has occured". --Konzertheld

Initially reported by: @wilcosworld as #TRAC561 
Refering to the manage page or manage entry section of the admin screen.
When you are searching for something using the search bar, and then hit the 'X' clear button, then select another value, (draft, published, scheduled, entry or page), the search box updates to reading "Type and wait to search for any entry component status:published".

As a side note, when you hit the 'x' clear button, it should un-select that search values selected.

**Comment by Konzertheld** [comment]
Updated title and initial comment as there is a new error when clearing the search box in 0.10.
