### ISSUE TITLE
Author URL for themes

### ISSUE THREAD

**Issue by HabariImporter** [habari/habari#29]
Initially reported by: @msi as #TRAC571 
I have this enhancement to create author URLs to display posts of a specified author. It's a new rewrite rule and a new action. If you change your theme code like

{{{
"<a href='" . URL::get( 'display_entries_by_author', array('author' => $post->author->username) ) .
	"'>" . $post->author->displayname . "</a>"
}}}

you will get a clickable link.

It works, but I don't like the idea of using the user name. WordPress has a so called ''nice name'' for the URL slug. I would like to have the same here in Habari, because my user name and the ''nice name'' are different. It's for security because a potential attacker will think both are the same. ;-)

**Comment by Konzertheld** [comment]
Closing as the discussion never lead to a desirable solution and also apparently the patch is gone.
