### ISSUE TITLE
Latest Log Entries Block Breaks Admin when Configured with Empty Number of Entries

### ISSUE THREAD

**Issue by chrismeller** [habari/habari#412]
Add the Latest Log Entries block to your dashboard. Hit the configure button. The default is empty (it's actually 8, behind the scenes). Hit save. Reload your admin. Watch PHP barf about your memory limit when trying to load all the entries in the log at once.

**Comment by HabariAssistant** [comment]
This issue was moved to habari/coredashblocks#3
