### ISSUE TITLE
Tag Archives including Excluded Terms 404

### ISSUE THREAD

**Issue by chrismeller** [habari/habari#462]
Going to the URL `/tag/foo bar -baz`, which supposedly should give me a normal tag archive page for posts with the tags "foo" and "bar", but *not* "baz" gives me a 404 status code, but otherwise appears to show the homepage.

**Comment by Konzertheld** [comment]
Closed because I can't reproduce. Showing posts having tags a, b but not c works fine on a fresh 0.10-alpha.
