### ISSUE TITLE
Dashboard Blocks Are Not Removed When Plugin Deactivated.

### ISSUE THREAD

**Issue by chrismeller** [habari/habari#463]
Just what it says. A plugin provides a dashboard block. If you add it, then the plugin is deactivated

**Comment by Konzertheld** [comment]
Dashboard blocks from deactivated plugins no longer generate errors as of https://github.com/habari/system/commit/cda246460695b651b6adc86776d4be1ad5b4a5b3 (though I do not know where it was fixed), so closing this and leaving only #10.
