### ISSUE TITLE
Entry/Page should not (only) refer to the entry's/page's feed

### ISSUE THREAD

**Issue by moeffju** [habari/habari#482]
By default, on a `display_entry` or `display_page` view, Habari only links to the single item's feed, due to https://github.com/habari/system/blob/master/classes/theme.php#L719.

This behaviour seems counter-intuitive and counter-productive to me as both a blog author and a blog subscriber. If I don't check carefully, I'll subscribe to an entry's feed that will never have new posts. This is clearly undesirable from both standpoints.

This can be overridden by overwriting `theme_feed_alternate` in the theme.php:

```php
        public function theme_feed_alternate( $theme )
        {
                return URL::get( 'atom_feed', array( 'index' => '1' ) );
        }
```

But this is clearly not the best solution.

**Comment by Konzertheld** [comment]
This is old, has had no discussion and I do not agree every post should have the site's global feed. On the opposite, pages that display a single entry should _not_ have it.
