### ISSUE TITLE
About 10KiB Sized blog post Causes the PHP to Allocate over 400MiB of RAM

### ISSUE THREAD

**Issue by martinvahi** [habari/habari#486]
<habari root>/user/cache

fills with multiple 420MiB semirandomly named files and when one tries to publish a small, about 10KiB sized, text based, article,

http://urls.softf1.com/2013/ttu/futuroarhivaar_1/idk6100-kodut%C3%B6%C3%B6-virtuaalmaailma-mikrotutvustus

the PHP tries to allocate over 400MiB of memory, which causes a virtual server process to crash.

Habari version 0.9

**Comment by Konzertheld** [comment]
Confirmed the fix in master works for both CURL and Sockets.
