### ISSUE TITLE
New tags page

### ISSUE THREAD

**Issue by Konzertheld** [habari/habari#596]
Not all of us like the tags page in the 0.9 admin. As it's completely broken in 0.10, we could use the opportunity to re-think it a bit. Here are my thoughts, feel free to add yours in the comments.
- I like the old tags page basically. It is ordered alphabetical and it shows me how often the tags are used. Those are the two basic things I expect from a page like this.
- There is no way to change that view in any way except filtering (this is maybe the one place where the JS direct search is appropriate). We definitely need sorting by frequency of occurrence.
- I would also like more statistics. I recently modified my tag cloud plugin to have my tags displayed in a high 25% - mid 50% - low 25% style. I can imagine something like that for the admin tags page, together with a chart like "25% of your overall tag usage is made by 5% of your tags" (10 of your 200 tags have been used 100 times each, but all the others together have only been used 3000 times).
- A really cool feature would be something that could help you use tags more often. You propably know the situation when you look at your hundreds of tags and accidentally see one and think, "oh hey, I have a tag for that? I could have used that there and there". I always forget to use some of my tags. No idea how to sensibly implement something to solve this in admin though.

Related #387

**Comment by Konzertheld** [comment]
Two more quick design studies.

![bildschirmfoto vom 2016-09-03 05 35 34](https://cloud.githubusercontent.com/assets/505380/18222527/7eb6c548-719a-11e6-8e19-9e22ad8890b6.png)
![bildschirmfoto vom 2016-09-03 05 37 33](https://cloud.githubusercontent.com/assets/505380/18222528/823598c0-719a-11e6-8d73-38b5fd4fde63.png)

**Comment by Konzertheld** [comment]
Adding fixed width and increasing the steps from green tone to tone:

![bildschirmfoto vom 2016-09-03 06 10 51](https://cloud.githubusercontent.com/assets/505380/18222616/35a36836-719d-11e6-95f5-1aee70ba7f39.png)

**Comment by Konzertheld** [comment]
There is work ongoing in https://github.com/habari/system/tree/fix_596

**Comment by Konzertheld** [comment]
Another thought: Is there a need to use AJAX on the tags page? Does that bring us any benefit? We replace the entire HTML anyway, we could as well just reload the page.

**Comment by Konzertheld** [comment]
Side note: The new list style lowers the number of tags per screen significantly. Not surprising, as we no longer use small font sizes. We'll see how this evolves in the next days.

**Comment by Konzertheld** [comment]
I played a bit with similarity stuff and came to the following conclusions:
1. Ordering all the tags by similarity is neither a doable task nor useful, having 350+ tags like I have. If it worked, it would move misspelled tags to their correct version, but it would also move a lot of nonsense.
2. Calculating the most similar tags (if any, using a threshold) for every tag is partly useful. It detects misspelled tags and a little bit more. It also detects a lot of nonsense. I think that could go in a plugin.
3. Most of my duplicate tags are not from misspelling but from semantics (verbs and nouns, composed words - those are common in German - etc). We can't do anything there.
4. To at least avoid misspelling, a similarity algorithm could go into the tag suggestions when adding tags to posts. Currently we only show tags starting with the letters entered. We could add similar tags, too, using Levenshtein or something like that. That would hopefully reduce the number of misspelled tags to near zero and therefore make a functionality to find those on the tags page unnecessary in core.

**Comment by miklb** [comment]
Finding similar tags would be useful I think, but certainly an enhancement, not a particularly important feature.

**Comment by Konzertheld** [comment]
![bildschirmfoto von 2016-11-07 17-48-33](https://cloud.githubusercontent.com/assets/505380/20066731/ea07c9ae-a512-11e6-94c6-ed41ca4676fd.png)
