### ISSUE TITLE
0.9.2 doesn't work under PHP 5.6.3

### ISSUE THREAD

**Issue by jniggemann** [habari/habari#613]
Using PHP 5.6.3 I get a white screen, the logs show the following error:
`mod_fcgid: stderr: PHP Fatal error:  Class name must be a valid object or a string in /var/www/habari/system/classes/theme.php on line 79`

**Comment by Konzertheld** [comment]
I don't have any problems running Habari 0.9.2 under PHP 5.6.7. Please give more instructions for reproduction.

**Comment by jniggemann** [comment]
Issue is reproduceable like as follows, but this time I get another error message.
- download latest habari and extract to folder
- try to run it using PHP 5.6.3
-> white screen

Apache errorlog shows `mod_fcgid: stderr: PHP Fatal error:  Call to a member function getName() on boolean in /var/www/virtual/account/html/habari/system/classes/themes.php on line 53`

This happens on multiple uberspace.de servers.

**Comment by chrismeller** [comment]
To be clear, are you talking about simply trying to launch the installer, or have you already provided an existing config file and DB?

**Comment by jniggemann** [comment]
The former, I'm trying to launch the installer.

**Comment by jniggemann** [comment]
Fixed (at least for me): Set libxml_disable_entity_loader to false. Maybe it's [this bug:](https://bugs.php.net/bug.php?id=62577)
```php
libxml_disable_entity_loader(false);
$themedata['info'] = simplexml_load_file( $theme_path . '/theme.xml' ) or die("Something is wrong, couldn't load theme.xml...");
```
