### ISSUE TITLE
Entries strip Emoji in content

### ISSUE THREAD

**Issue by HabariAssistant** [habari/habari#623]
_From @miklb on September 3, 2016 16:40_

Using .10, post an entry with an emoji 👍

Publish

Emoji is stripped from content

_Copied from original issue: habari/system#79_

**Comment by mikelietz** [comment]
Maybe they just need to be made valid shortcodes? Seems to me a simple plugin could knock this one out.

**Comment by Konzertheld** [comment]
I can't reproduce this using 0.10 and Wazi as theme.

**Comment by miklb** [comment]
Doesn't look like I reproduce now either.
