### ISSUE TITLE
Rebuild plugins page in admin (0.10)

### ISSUE THREAD

**Issue by Konzertheld** [habari/habari#628]
Initially I just wanted to replace the nonfunctional search with a faceted search, but there is no FormUI at all in that page's code. Also I came up with an idea: With faceted search, there could be a filter "user contributions" or something like that, to search in the addons catalog instead of just on that page. So I think this page deserves its own ticket.

**Comment by miklb** [comment]
Does the addon catalog work? I had submitted to it but never seemed to be right.

**Comment by Konzertheld** [comment]
It did work a while ago. I don't know about now, but that was meant for the future anyway. I just wanted to write it down.

**Comment by mikelietz** [comment]
To both points: The plugins page search box is actually just a filter. It works in 0.9.2, but is only searching on the page.

The addons catalog was broken when last I complained about it. It needs to be debugged piece by piece, I believe.

**Comment by Konzertheld** [comment]
I specified the title, I am talking about 0.10 only here. AFAIK there is no faceted search in 0.9.x, and also, we should really focus on 0.10 and no longer work on a 0.9.x release. I know that the search boxes in the 0.9 admin are only page filters, but I think some of them could be more.

**Comment by Konzertheld** [comment]
I noticed the faceted search can easily be used with our old page filter search so I just brought that back, see the above commit from the corresponding branch.

**Comment by Konzertheld** [comment]
![bildschirmfoto vom 2016-10-25 03-29-47](https://cloud.githubusercontent.com/assets/505380/19670121/1e803cba-9a65-11e6-8550-ad1dbd1d43e7.png)

**Comment by Konzertheld** [comment]
As the addon catalog is apparently broken and it is currently no priority to restore its functionality, I fixed the rest of the stuff I intended with this ticket and closed it.
