### ISSUE TITLE
Reset password broken in .10

### ISSUE THREAD

**Issue by Konzertheld** [habari/habari#631]
Form does not change to reset password view.

**Comment by Konzertheld** [comment]
Seems to work in Firefox.

**Comment by Konzertheld** [comment]
Hmm, can't reproduce it anymore, maybe just a lag / glitch due to system updates.

**Comment by miklb** [comment]
Having issue in desktop Safari Tech Preview

Rest link sends email, ex `http://mb.dev/auth/password_reset?id=1&hash=kvpz7Vdmls` however following that link loads a normal login screen.

**Comment by Konzertheld** [comment]
It is intended that you are redirected to the login screen. You should receive a mail with a new password. Can you make sure you did not?

**Comment by miklb** [comment]
I did not receive a second email.
