### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by illyaking** [habari/habari#654]
Hello,
I've installed Habari on my site at notes.illyaking.com. Is there a way I can force the SSL on it? I  did a self-install.
-Illya

**Comment by chrisjdavis** [comment]
If what you are asking is how to force all incoming http requests to redirect to https, then that should be done with an apache directive in your htaccess file, or in the apache conf file itself.

**Comment by miklb** [comment]
There is also [documentation for SSL with nginx](http://wiki.habariproject.org/en/Installation_using_Nginx#SSL)

**Comment by illyaking** [comment]
Oh... I see. Okay, thank you. I appreciate it.
