### ISSUE TITLE
Localizable hotkeys

### ISSUE THREAD

**Issue by HabariImporter** [habari/habari#80]
Initially reported by: @helpy as #TRAC1065 
It would be very helpful to make the hotkeys localizable.

I do not know how to do this! I think this should not be done with _t("Q"), _t("N") ... This would be hard for the translators to figure out, what a single letter stands for.

Surely there are some ways to make localization of hotkeys work. Some ideas:

'''1.''' In the Text of the menu items a letter is marked with brackets "[]" like _t("[D]ashboard"). For displaying the menu text the brackets could be filtered out. But this way only letters could be used, which are part of the menu text. The hotkey "X" for the menu item "Logout" would not be possible.

'''2.''' Maybe _t("[X] Logout"), _("[D] Dashboard") ... would be a solution (or similar: _t("Logout [X]"), _("Dashboard [D]") ... ).
==> I would prefer this solution!

cu, guido

**Comment by Konzertheld** [comment]
This issue was moved to habari/system#80
