### ISSUE TITLE
Conflict between length of localized strings and width of UI elements

### ISSUE THREAD

**Issue by HabariImporter** [habari/habari#81]
Initially reported by: @helpy as #TRAC1066 
The width of the admin menu is static! If a localized text is too
long, the text overlaps the hotkey. For German language I can use a
shorter word, but it could be possible that in ohter languages the
translations are longer!

This is also a problem with other UI elements. Example: On dashboard
the label "Add Item" left of the drop down element "[List of dashboard modules]". If the localized text of "Add Item" is too long it overlaps the drop down element.

[https://trac.habariproject.org/habari/ticket/1000 Ticket #TRAC1000] is one part of the problem.

**Comment by HabariAssistant** [comment]
This issue was moved to habari/system#81
