### ISSUE TITLE
Opening admin menu item in new tab shows loading circle on original tab

### ISSUE THREAD

**Issue by HabariImporter** [habari/habari#82]
Initially reported by: @caius as #TRAC1068 
Steps to reproduce:
- Go to the admin
- Open an item in the (top left) menu in a new tab. (In safari/osx I cmd-clicked it.)

What I expected to happen:
- Item I clicked opens it's page in a new tab

What actually happens:
- Item I clicked opens it's page in a new tab
- Loading icon shows up on the original tab and spins forevermore.

**Comment by HabariAssistant** [comment]
This issue was moved to habari/system#82
