### ISSUE TITLE
Blocks UI

### ISSUE THREAD

**Issue by HabariImporter** [habari/habari#98]
Initially reported by: @ddebernardy as #TRAC1154 
I was having a chat with Mike on IRC regarding blocks/widgets UI. The part of this video that shows widget management is very close to what I was trying to describe:

http://www.squarespace.com/tour/

**Comment by Konzertheld** [comment]
I have no idea what this ticket is supposed to say and the video from the OP is no longer available, so closing. If @ddebernardy or @mikelietz remember, feel free to re-open.
